services:
    App\Champion\Domain\Repository\ChampionRepositoryInterface:
        alias: App\Champion\Infrastructure\Persistence\Doctrine\Repository\DoctrineChampionRepository

    App\Champion\Application\Port\RiotChampionProviderInterface:
        alias: App\Champion\Infrastructure\Adapter\RiotChampionProvider

    App\Champion\Application\Port\ChampionAssetDownloaderInterface:
        alias: App\Champion\Infrastructure\Adapter\ChampionAssetDownloader

    app.asset_downloader.champion:
        class: App\SharedContext\Infrastructure\Asset\GameAssetDownloader
        arguments:
            $cdnBaseUrl: 'https://ddragon.leagueoflegends.com/cdn/%%s/img/champion/%%s'
            $imagesDir: '%app.champions_images_dir%'
