services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\GameData\Domain\Repository\QueueRepositoryInterface:
        alias: App\GameData\Infrastructure\Persistence\Doctrine\Repository\DoctrineQueueRepository

    App\GameData\Domain\Repository\GameModeRepositoryInterface:
        alias: App\GameData\Infrastructure\Persistence\Doctrine\Repository\DoctrineGameModeRepository

    App\GameData\Domain\Repository\GameTypeRepositoryInterface:
        alias: App\GameData\Infrastructure\Persistence\Doctrine\Repository\DoctrineGameTypeRepository

    App\GameData\Domain\Repository\MapRepositoryInterface:
        alias: App\GameData\Infrastructure\Persistence\Doctrine\Repository\DoctrineMapRepository

    App\GameData\Domain\Repository\SeasonRepositoryInterface:
        alias: App\GameData\Infrastructure\Persistence\Doctrine\Repository\DoctrineSeasonRepository

    App\GameData\Application\Port\RiotStaticDataProviderInterface:
        alias: App\GameData\Infrastructure\Client\RiotStaticDataProvider

    App\GameData\Application\Port\ItemAssetDownloaderInterface:
        alias: App\GameData\Infrastructure\Adapter\ItemAssetDownloader

    app.asset_downloader.item:
        class: App\SharedContext\Infrastructure\Asset\GameAssetDownloader
        arguments:
            $cdnBaseUrl: 'https://ddragon.leagueoflegends.com/cdn/%%s/img/item/%%s'
            $imagesDir: '%app.items_images_dir%'
