services:
    App\Summoner\Domain\Repository\SummonerRepositoryInterface:
        alias: App\Summoner\Infrastructure\Persistence\Doctrine\Repository\DoctrineSummonerRepository
    
    App\Summoner\Application\Port\RiotSummonerProviderInterface:
        alias: App\Summoner\Infrastructure\Adapter\RiotSummonerProvider

    App\Summoner\Application\Port\RiotLeagueProviderInterface:
        alias: App\Summoner\Infrastructure\Adapter\RiotLeagueProvider
