services:
    App\Summoner\Domain\Repository\SummonerRepositoryInterface:
        alias: App\Summoner\Infrastructure\Persistence\Doctrine\Repository\DoctrineSummonerRepository

    App\Summoner\Application\Port\RiotSummonerAdapterInterface:
        alias: App\Summoner\Infrastructure\Adapter\RiotSummonerProvider
