# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_client:
        scoped_clients:
            riot.api.dataleague:
                scope: 'https://europe.api.riotgames.com'
                headers:
                    X-Riot-Token: '%env(string:API_RIOT_TOKEN)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
