framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: lolanalytics
                        type: direct
                        default_publish_routing_key: async
                    queues:
                        lolanalytics_async:
                            binding_keys: [async]
                retry_strategy:
                    service: App\SharedContext\Infrastructure\Messenger\ServerLimitRetryStrategy

            failed:
                dsn: 'doctrine://default?queue_name=failed'

        default_bus: command.bus

        buses:
            command.bus: ~
            query.bus: ~
            message.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - dispatch_after_current_bus

        routing:
            App\Summoner\Application\Command\ImportSummonerCommand: async