version: '3.9'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - "8888:8080"

  mail:
      image: maildev/maildev
      ports:
        - "1080:1080"
        - "1025:1025"

  php:
    build:
      context: ./docker/web
      target: app_php
    restart: unless-stopped
#    environment:
#      APP_SERVER_NAME: lolanalytics-dev.fr
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

volumes:
  db-data: