controllers:
    resource: ../src/
    type: attribute
    exclude:
        - '../src/Match/Presentation/Api/'

match_api:
    resource: ../src/Match/Presentation/Api/
    type: attribute
    prefix: /api/matches
    
summoner_api:
    resource: ../src/Summoner/Presentation/Api/
    type: attribute
    prefix: /api/summoners


champion_api:
    resource: ../src/Champion/Presentation/Api/
    type: attribute
    prefix: /api/champions

game_data_api:
    resource: ../src/GameData/Presentation/Api/
    type: attribute
    prefix: /api/game-data
