parameters:
    app.champions_images_dir: '%kernel.project_dir%/public/images/champions'
    app.items_images_dir: '%kernel.project_dir%/public/images/items'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Model/*'
            - '../src/Match/Domain/Model/*'
            - '../src/GameData/Domain/Model/*'
            - '../src/Summoner/Domain/Model/*'
            - '../src/Champion/Domain/Model/*'
            - '../src/Auth/Domain/Model/*'
            - '../src/League/Domain/Model/*'
            - '../src/Infrastructure/SharedContext/Framework/Symfony/Kernel.php'

imports:
    - { resource: services/match.yaml }
    - { resource: services/game_data.yaml }
    - { resource: services/summoner.yaml }
    - { resource: services/champion.yaml }
    - { resource: services/auth.yaml }
    - { resource: services/league.yaml }
    - { resource: services/shared_context.yaml }
