# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude: 
            - '../src/Domain/Model/*'
            - '../src/Infrastructure/SharedContext/Framework/Symfony/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Version Bounded Context
    App\Domain\Version\Service\VersionServiceInterface:
        alias: App\Infrastructure\Version\Service\RiotApiVersionService

    App\Domain\Version\Repository\VersionRepositoryInterface:
        alias: App\Infrastructure\Version\Repository\DoctrineVersionRepository

    # CQRS Buses
    App\Application\SharedContext\Bus\CommandBusInterface:
        alias: App\Infrastructure\Bus\MessengerCommandBus

    App\Application\SharedContext\Bus\QueryBusInterface:
        alias: App\Infrastructure\Bus\MessengerQueryBus
        
    # Infrastructure Services
    App\Infrastructure\Version\Service\RiotApiVersionService:
        arguments:
            $dataDragonClient: '@Zeggriim\RiotApiDataDragon\DataDragon\DataDragonApiInterface'



#    App\Domain\Version\Service\VersionServiceInterface:
#        alias: App\Infrastructure\RiotApi\Service\RiotApiVersionService
#
#    App\Domain\RiotApi\Repository\VersionRepositoryInterface:
#        alias: App\Infrastructure\RiotApi\Repository\DoctrineVersionRepository
#
#    App\Infrastructure\RiotApi\Service\RiotApiVersionService:
#        arguments:
#            $dataDragonClient: '@Zeggriim\RiotApiDataDragon\DataDragon\DataDragonApiInterface'
