ServerName lolanalytics-dev.fr
<VirtualHost *:80>
    DocumentRoot /var/www/public
    DirectoryIndex /index.php


    #Debut Regle(s)/parametres(s) de securite - NE PAS MODIFIER, NE PAS SUPPRIMER, NE PAS COMMENT
    #
    # Desactivation des methodes TRACE et TRACK du protocole HTTP pour eviter des problemes de S
    # de type cross-site scripting (XST) et d'interception de données utilisateurs
    RewriteEngine on
    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
    RewriteRule .* - [F]

    # Protection contre les failles par injection SQL
    # Faille dieseRefRef (Obligatoire)
    RewriteCond ${QUERY_STRING} .*(/\*|benchmark) [NC]
    RewriteRule .* - [R=406,L]

    <Directory /var/www/public>
        Options -MultiViews +FollowSymLinks +Indexes
        AllowOverride All
        Order Allow,Deny
        Allow from All
        Require all granted
        # Symfony rewrite rule

        # sets the HTTP_AUTHORIZATION header removed by Apache
        RewriteCond %{HTTP:Authorization} .
        RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

        # If the requested filename exists, simply server it.
        # We only want to let Apache serve files and not directories.
        RewriteCond %{REQUEST_FILENAME} -f
        RewriteRule ^ - [L]

        # Rewrite all other queries to the front controller
        RewriteRule ^ /index.php [L]
    </Directory>

    # uncomment the following lines if you install assets as symlinks
    # or run into problems when compiling LESS/Sass/CoffeeScript assets
    # <Directory /var/www/project>
    #     Options FollowSymlinks
    # </Directory>

    # optionally disable the fallback resource for the asset directories
    # which will allow Apache to return a 404 error when files are
    # not found instead of passing the request to Symfony
    <Directory /var/www/project/public/bundles>
        FallbackResource disabled
    </Directory>
    ErrorLog /var/log/apache2/project_error.log
    CustomLog /var/log/apache2/project_access.log combined

    # optionally set the value of the environment variables used in the application
    #SetEnv APP_ENV prod
    #SetEnv APP_SECRET <app-secret-id>
    #SetEnv DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name"
</VirtualHost>
